#单位是秒
time: 7200

#§作为颜色代码的开头 并非是游戏内的&
titleInventory: §4§l简单的测试
noPermissMsg: §4§l你没有权限使用这个命令
noItemMsg: §6§l[随机商城] §4你没有这个物品/你所需的数量不足。无法贩卖
#一定要有三个值
#%d 对应的是 数量 %fl 对应的是金钱 下一个是 %s 当前金钱
moneyMsg: §6§l[随机商城] §a您卖出去了 %fl 个，现在得到了 %s 元. 现在您有 %s
announcement: §6§l[随机商城] 列表已刷新，请输入/zmss open打开商城查看


#存储数据的地方[尽量不要随意更改]
data: